NAME: "floor_baseline"
MODEL:
  backbone:
    type: HRNetW18SmallV2
  weights: /home/julianzhang/projects/SMore-Segmentation/pretrained_model/hrnet_w18_small_model_v2.pth
  head:
    type: HRHead
    with_se_cat: True

  loss:
    - type: DiceCustom
      dice_pow: [2, 3, 3, 3, 3, 3, 3]
      weights: 2.0
    - type: BootstrapCE
      weights: 0.4

  dropout: 0.0
  channels: 3
  num_classes: 7
  ignore_label: 7

DATA:
  preprocessor:
    - type: Rescale
      output_size: [512, 512]
      # [width, height]
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  value_scale: 255
  label_map:
    - background
    - closet
    - batchroom
    - livingroom
    - bedroom
    - hall
    - balcony
    - opening
    - wall

  train_data:
    type: FloorPlanDataset
    data_name: train
    layers: 3
    root: '/home/julianzhang/datasets/5210/'
    data_path:
        - /home/julianzhang/projects/SMore-Segmentation/exps_julian/poc/06-floorplan/lists/train.txt
      
  eval_data:
    - type: FloorPlanDataset
      data_name: val
      layers: 3
      root: '/home/julianzhang/datasets/5210/'
      data_path:
        - /home/julianzhang/projects/SMore-Segmentation/exps_julian/poc/06-floorplan/lists/test.txt

    
  test_data:
    - type: FloorPlanDataset
      data_name: test
      layers: 3
      root: '/home/julianzhang/datasets/5210/'
      data_path:
        - /home/julianzhang/projects/SMore-Segmentation/exps_julian/poc/06-floorplan/lists/test.txt

evaluate:
  evaluators:
    - type: PixelBasedEvaluator
      metrics:
        - type: PixelBasedMeanIOU
        - type: MeanPrecision
        - type: MeanRecall

TRAIN:
  optimizer:
    type: SGD
    lr: 0.01
  lr_scheduler:
    type: PolyLR
    max_iter: 40000
    power: 0.9
    warmup_iter: 700
  data_argumentation:
    - type: RandomRotation
      prob: 0.3
      angle: [-10, 10]
    - type: RandomRotation
      prob: 0.3
      angle: [90, 90]
    - type: RandomHorizontalFlip
      prob: 0.5
    - type: RandomVerticalFlip
      prob: 0.5
    - type: RandomScale
      scale: [0.9, 1.1]
      prob: 0.7
    - type: RandomCrop
      output_size: [512, 512]
    - type: ColorJitter
      brightness: 0.4
      contrast: 0.4
      prob: 0.6

  max_iter: 40000
    ckpt_freq: 2000 # the same as eval freq.
    print_freq: 50
    batch_size_per_gpu: 16

EVAL:
  type: SimpleInference
  batch_size_per_gpu: 1